### ISSUE TITLE
Fix incorrect markdown in homework README

### ISSUE THREAD

**Issue by KaloyanSimitchiyski** [amarazov/mccpy#1]
Can you fix the incorrect markdown in **mccpy/week02-03/homework_1**?

[Link to README](https://github.com/amarazov/mccpy/tree/master/week02-03/homework_1#L9), the issue is in section **A1** in the **RMS deviation**.

**Comment by KaloyanSimitchiyski** [comment]
There are also other markdown problems in the said README.

**Comment by amarazov** [comment]
Mark down does not render LaTeX yet. I am open to suggestions how this can be made more readable.

**Comment by KaloyanSimitchiyski** [comment]
An easy solution would be to use an external service like [iTex2Image](http://www.sciweavers.org/free-online-latex-equation-editor) or [latex2png](http://latex2png.com/) and then to embed the generated image in the README.
